arm:
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  shoulder_pan_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: shoulder_pan_joint
      pid: {p: 200, d: 1, i: 1 }
  shoulder_lift_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: { p: 200, d: 1, i: 1 }
  elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: { p: 140, d: 0.01, i: 0.01 }
  wrist_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_1_joint
    pid: { p: 140, d: 0.01, i: 0.01 }
  wrist_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_2_joint
    pid: { p: 140, d: 0.01, i: 0.01 }
  wrist_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_3_joint
    pid: { p: 140, d: 0.01, i: 0.01 }